site_name: {{cookiecutter.repo_name}}
site_description: {{cookiecutter.description}}
site_author: {{cookiecutter.author_name}}

theme:
  name: material
  logo: betclic_logo.png
  favicon: betclic_logo.png

nav:
  - Home: index.md
  - Code Reference: reference/SUMMARY.md

plugins:
- search
- mkdocstrings:
    default_handler: python
    watch:
    - src
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocs-jupyter
- mermaid2

repo_url: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.repo_name}}

